### ISSUE TITLE
Make error with printf

### ISSUE THREAD

**Issue by Epsylene** [msqrt/ssgl#2]
The make recipe fails on `impl/gl_helpers.h` with the following error message (on Ubuntu 20.04.4 and Windows with MSYS2) :
```shell
impl/gl_helpers.h: In member function 'Buffer::operator std::vector<T>() const':
impl/gl_helpers.h:30:39: error: there are no arguments to 'printf' that depend on a template parameter, so a declaration of 'printf' must be available [-fpermissive]
   30 |                 if (size % sizeof(T)) printf("warning: buffer and vector types don't align");
      |                                       ^~~~~
```
Adding the -fpermissive flag makes this error go away.

**Comment by msqrt** [comment]
Thanks for noting this! The file didn't need to print before adding the `std::vector` converters, and `cstdio` was thus erroneously not included before it. I pushed [a fix](https://github.com/msqrt/ssgl/commit/7a634ede7d54c184e3c5d9a7922022f8c514c6c0) that works on all of my setups.

**Comment by Epsylene** [comment]
No problem, thank you for your work !
